language: rust
sudo: false

cache: cargo

os:
- linux
- osx

rust:
- stable
- beta
- nightly

matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo test
  - cargo test --no-default-features
  - cargo run --manifest-path ./example_project/Cargo.toml
