language: rust
sudo: false

cache: cargo

os:
  - linux
  - osx

rust:
  - 1.14.0
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
    - cargo build --verbose
    - cargo test --verbose --all-features
