language: rust

cache: cargo

os:
- linux
- osx

rust:
- stable
- beta
- nightly

matrix:
  fast_finish: true

before_install:
  - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
    rustup self update &&
    rustup component add rustfmt clippy;
    fi

script:
  - if [ "$TRAVIS_RUST_VERSION" != "nightly" ]; then
    cargo fmt --all -- --check &&
    cargo clippy --all --tests --examples --features git2,chrono,semver;
    fi
  - cargo test
  - cargo test --features git2,chrono,semver
  - cargo run --manifest-path ./example_project/Cargo.toml
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
    cargo test --doc --features nightly README;
    fi
