[package]
name = "built"
version = "0.1.0-rc1"
description = "Provides a crate with information from the time it was built."
repository = "https://github.com/lukaslueg/built"
authors = ["Lukas Lueg <lukas.lueg@gmail.com>"]
license = "MIT"
keywords = ["cargo", "build"]

[features]
default = ["serialized_git", "serialized_time", "serialized_version"]
serialized_git = ["git2"]
serialized_time = ["time"]
serialized_version = ["semver"]

[dependencies]
toml = "0.2"
semver = { version="0.6", optional=true }
time = { version="0.1", optional=true }
git2 = { version="0.6", optional=true, default-features = false, features = [] }

[dev-dependencies]
tempdir = "0.3"
semver = "0.6"
time = "0.1"
